magento/urls.py
            # MAGENTO URLS






from django.conf.urls import url
from django.contrib.auth import views
from .views import *

urlpatterns = [
	url(r'^vendor_register$', VendorRegister.as_view(), name="mag_vend_register"),
	url(r'^vendor_login$', VendorLogin.as_view(), name="mag_vend_login"),
	url(r'^vendor_forget-password$', VendorForgetPassword.as_view(), name="mag_vend_forget_password"),
	url(r'^vendor_dashboard$',VendorDashboard.as_view(),name="mag_vend_dashboard"),
	url(r'^merchant-register$', MerchantRegister.as_view(), name="mag_mer_register"),
	url(r'^merchant-login$', MerchantLogin.as_view(), name="mag_mer_login"),
	url(r'^merchant-forget-password$', MerchantForgetPassword.as_view(), name="mag_mer_forget_password"),
	url(r'^merchant-dashboard$',MerchantDashboard.as_view(),name="mag_mer_dashboard"),
	url(r'^merchant-add-products$',AddProducts.as_view(),name="mag_mer_add_product"),
	url(r'^merchant-remove-product$',RemoveProduct.as_view(),name="mag_mer_remove_product"),
	url(r'^merchant-logout/$',views.logout, {'next_page': '/magento/merchant-login'}),
	url(r'^vendor-logout/$',views.logout, {'next_page': '/magento/vendor_login'}),
	url(r'^payment$',PaypalAdaptivePayment.as_view(),name="mag_mer_paypal"),
	url(r'^payment/fail$',FailPayment.as_view(),name="mag_mer_paypal_fail"),
	url(r'^vendor-add-products$',AddVendorProduct.as_view(),name="mag_ven_add_product"),
	url(r'^vendor-remove-products$',VendorRemoveProduct.as_view(),name="mag_ven_remove_product"),
	url(r'^allow-mercahnts$',ControlMerchantAccess.as_view(),name="allowmerchants"),
	url(r'^vendor_update_paypal$',PaypalEmail.as_view(),name='vendor_update_paypal'),
	url(r'^availability$', ProductAvailable.as_view(), name="product_available"),
	url(r'^merchant_uninstall$', UninstallMerchant.as_view(), name="merchant_uninstall"),
	url(r'^view_varient_product$', ViewVarientProduct.as_view(), name="view_varient_product"),
]

merchants/urls.py
from django.conf.urls import url
from .views import AddMerchant, AddProduct, DeleteMerchant


urlpatterns = [
	url(r'^add$', AddMerchant.as_view()),
	url(r'^delete$', DeleteMerchant.as_view()),
	url(r'^products/add$', AddProduct.as_view()),
	url(r'^products/delete$', AddProduct.as_view()),
]

mvp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

#from django.contrib.auth.models import User
#from rest_framework import routers, serializers, viewsets
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT, 'show_indexes': 'True'}),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}),
    url(r'^mvpadmin/',include('mvpadmin.urls')),
    url(r'^images/', include('images.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^apis/', include('apis.urls')),
    url(r'^merchants/', include('merchants.urls')),
    url(r'^vendors/', include('vendors.urls')),
    url(r'orders/', include('orders.urls')),
    url(r'^magento/',include('magento.urls')),
    url(r'^', include('shopify.urls')),
]

# urlpatterns += static(r'^media/', document_root=settings.MEDIA_ROOT)

images/models.py
from __future__ import unicode_literals
from django.db import models
from shopify.models import Products, Account
from django.conf import settings
import time
import PIL
from PIL import Image
import os
from django.utils import timezone

def get_image_path(self,filename):
	file_path=settings.MEDIA_ROOT

	save_path = ''
	thumbnails=Thumbnails.objects.all()


	if (self.token):
		file_name=self.token+"_"+filename
		self.image_name=file_name
		file_path=file_path + "/products/"+str(self.token)
		save_path="products/"+str(self.token)+"/"+file_name
	else:
		currenttime=str(int(time.time()))
		file_name=currenttime+"_"+filename
		self.image_name=file_name
		file_path=file_path + "/products/"+str(currenttime)
		save_path="products/"+str(currenttime)+"/"+file_name
		if(not os.path.exists(file_path)):
			os.makedirs(file_path)
		for thumbnail in thumbnails:
			img = Image.open(self.image)
			width = thumbnail.width
			height = thumbnail.height
			original_width, original_height = img.size
			new_width = width
			if int(original_width) < width:
				new_width = original_width
			img = img.resize((new_width,height), PIL.Image.ANTIALIAS)
			filename=file_path+"/"+str(width)+"_"+file_name
			img.save(filename)
		self.token = currenttime


	# if(self.product):
	# 	file_path=file_path + "/products/"+str(self.product.id)
	# 	save_path="products/"+str(self.product.id)+"/"+file_name
	# 	if(not os.path.exists(file_path)):
	# 		os.makedirs(file_path)
	# 	for thumbnail in thumbnails:
	# 		img = Image.open(self.image)
	# 		width = thumbnail.width
	# 		height = thumbnail.height
	# 		img = img.resize((width,height), PIL.Image.ANTIALIAS)
	# 		filename=file_path+"/"+str(width)+"_"+file_name
	# 		img.save(filename)
		#print  'product_{0}/{1}'.format(self.product.id, filename)
	return save_path


class Images(models.Model):
	user = models.ForeignKey(Account, on_delete=models.CASCADE)
	product = models.ForeignKey(Products, on_delete=models.CASCADE, null=True)
	image=models.ImageField(upload_to=get_image_path, default='default/image.jpg', max_length=500)
	image_name=models.CharField(max_length=200,blank=True,null=True)
	created_date=models.DateTimeField(default=timezone.now)
	updated_date=models.DateTimeField(default=timezone.now)
	token = models.CharField(max_length=50, blank=True)
	def __str__(self):

		return str(self.id)


class Thumbnails(models.Model):
	width=models.IntegerField()
	height=models.IntegerField()

magento/models.py
from __future__ import unicode_literals

from django.db import models
from orders.models import Orders
# Create your models here.

class PaypalAdaptive(models.Model):
    order = models.ForeignKey(Orders, blank=True, null=True,on_delete=models.CASCADE)
    uiid = models.CharField(max_length=500)
    pay_key = models.CharField(max_length=500)
    status = models.BooleanField(default=False)

magento/views.py
                        					# MAGENTO VIEWS


import binascii
import os
from passlib.hash import django_pbkdf2_sha256 as handler
from django.views.generic import TemplateView,View
from .models import *
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import HttpResponse
from django.shortcuts import render
from bs4 import BeautifulSoup
from django.utils.decorators import method_decorator
from .decorators import session_check,merchant_session_check
from django.contrib import messages
from shopify.models import Account,Products,Categories,Commission,ApiAuth
from itertools import groupby
from collections import OrderedDict
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
import datetime
import pycountry,requests,json
from validate_email import validate_email
from django.conf import settings
import uuid
from rauth.service import OAuth1Service
import requests
import urllib.parse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from passlib.hash import django_pbkdf2_sha256 as handler
from mailjet_rest import Client
from merchants.models import AccountDetail, ProductDetail, AccessToken,DenyAccess,MerchantShopeCredentials
from shopify.utils.userdetails import UserDetail
import base64
from orders.models import Orders,OrderProducts
from .models import PaypalAdaptive
from django.db.models import Sum
from vendors.models import VendorsShopCredentials
from images.models import Images
mailjet = Client(auth=(settings.MAILJET_API_KEY, settings.MAILJET_API_SECRET))

def send_template(emailid, Vars, template_id):
	data = {
		'FromEmail': 'info@fashioncircle.de',
		'FromName': 'Chris Weber',
		'MJ-TemplateID': template_id,
		'MJ-TemplateLanguage': True,
		'Recipients': [
			{ "Email": emailid}
		],
		'Vars': Vars
	}
	result = mailjet.send.create(data=data)
	return



class VendorRegister(TemplateView):
	template_name = 'vendor/mag_vend_register.html'

	def post(self, request, *args, **kwargs):
		response={}

		context = super(VendorRegister, self).get_context_data()
		name = request.POST['name']

		email=request.POST['email']
		platform=request.POST['platform']
		website=request.POST['website']
		country=request.POST['country']
		api_key ="pbkdf2_sha256$29000$p7lpJChcK4Lo$IHMul9j5lcPNJP4f/W1nXZknVi2N+GJIR1tZCo5C7uM="
		data ={"api_key":api_key,"name":name,"email":email,"platform":platform,"website":website,"country":country}
		headers={'HTTP_API_KEY':'de'}
		url=  settings.SITE_URL+'/vendors/add'
		try:
			posted=requests.post(url,params=data,headers=headers)
			response=posted.text


		except Exception as r:
			response['exception']=r

		return HttpResponse(json.dumps(response))

	def get_context_data(self, *args, **kwargs):
		context = super(VendorRegister, self).get_context_data(**kwargs)
		all_countries = []

		countries_list = list(pycountry.countries)
		for country in countries_list:
			all_countries.append(country.name)
		context['all_countries']=all_countries
		return context





class VendorLogin(TemplateView):
	template_name = 'vendor/mag_vend_login.html'
	def post(self, request, *args, **kwargs):

		response={}
		context = super(VendorLogin, self).get_context_data()
		email = request.POST['loginemail']
		password = request.POST['loginpassword']
		email_obj=Account.objects.filter(emailid=email)
		if not email_obj:
			response['emailerror']='email'
		else:
			status=email_obj[0].status
			if status==0:
				response['status']='status'
				return HttpResponse(response)
			added_shop=email_obj[0].added_shop
			if added_shop!='yes':
				response['shop']='shop'
				return HttpResponse(response)

			# print ('email matched')
			hash_password = email_obj[0].password
			verify_password = handler.verify(password, hash_password)
			print ('\n\n' +str(verify_password))
			if verify_password is False:
				response['passworderror']='password'
			else:
				token=email_obj[0].token
				request.session['vendor_token'] = token
				print (request.session['vendor_token'])
				response['success']='success'
		return HttpResponse(response)


		# email=request.POST['email']
		# platform=request.POST['platform']
		# website=request.POST['website']
		# country=request.POST['country']
		# api_key ="pbkdf2_sha256$29000$p7lpJChcK4Lo$IHMul9j5lcPNJP4f/W1nXZknVi2N+GJIR1tZCo5C7uM="
		# data ={"api_key":api_key,"name":name,"email":email,"platform":platform,"website":website,"country":country}
		# headers={'HTTP_API_KEY':'de'}
		# url=  settings.SITE_URL+'/vendors/add'
		# try:
		# 	posted=requests.post(url,params=data,headers=headers)
		# 	response=posted.text
		#
		#
		# except Exception as r:
		# 	response['exception']=r


	def get_context_data(self, *args, **kwargs):

		context = super(VendorLogin, self).get_context_data(**kwargs)
		all_countries = []

		countries_list = list(pycountry.countries)
		for country in countries_list:
			all_countries.append(country.name)
		context['all_countries']=all_countries
		return context

class VendorForgetPassword(TemplateView):

	template_name = 'vendor/mag_vend_forget_password.html'

	def get_context_data(self, *args, **kwargs):
		context = super(VendorForgetPassword, self).get_context_data(**kwargs)
		return context

	def post(self, request, *args, **kwargs):
		response={}
		email=request.POST.get("email")
		try:
			account=Account.objects.get(emailid=email)
			if account.status==0:
				response['status']=0
				response['msg']="This is a inactive account. Contact with administrator to activate your account."
			elif account.added_shop=="no":
				response['status']=0
				response['msg']="There is no shop associated with this account."
			elif account.platform !="Magento":
				response['status']=0
				response['msg']="This is not right platform for this email. This email is associated with Magento."
			else:
				password = binascii.hexlify(os.urandom(16)).decode()
				encrypted = handler.encrypt(password)
				account.password=encrypted
				account.save()
				first_name = account.first_name
				Vars = {"first_name": first_name, "merchant_name": account.platform,"password":password}
				template_id = "253891"
				send_template(email, Vars, template_id)
				response['status']=1
				response['msg']="New password is send to "+email+". Please check your email."
		except Account.DoesNotExist:
			response['status']=0
			response['msg']="There is no account associated with this email."
		return HttpResponse(json.dumps(response), content_type='application/json')


class VendorDashboard(TemplateView):

	template_name = 'vendor/mag_vend_dashboard.html'

	def get(self, request, *arg, **kwargs):
		try:
			headers = {'Accept': 'application/json'}
			token=request.session['vendor_token']
			#---------Merchant Details And Megento Auth key and secret-------
			vendor = Account.objects.get(token=token)
			order_id_lis=[]
			final_lis=[]
			credentials = VendorsShopCredentials.objects.get(vendor__id=vendor.id)
			if credentials.access_token:
				request.session["access_token"] = credentials.access_token
				request.session["access_token_secret"] = credentials.access_token_secret
			MAGENTO_HOST = vendor.website
			MAGENTO_API_BASE = '%s/api/rest/' % MAGENTO_HOST
			magento = OAuth1Service(
				name               = 'fashion_circle',
				consumer_key       = credentials.key,
				consumer_secret    = credentials.secret,
				request_token_url  = '%s/oauth/initiate' % MAGENTO_HOST,
				access_token_url   = '%s/oauth/token' % MAGENTO_HOST,
				authorize_url      = '%s/admin/oauth_authorize' % MAGENTO_HOST,
				SITE_URL           = MAGENTO_API_BASE
				)
			if 'access_token' not in request.session:
				oauth_token = request.GET.get('oauth_token')
				oauth_verifier = request.GET.get('oauth_verifier')
				if not oauth_token and not oauth_verifier:
					request_token, request_token_secret = magento.get_request_token(method='POST', params={'oauth_callback':'{}/magento/vendor_dashboard'.format(settings.SITE_URL)})
					credentials.request_token = request_token
					credentials.request_token_secret = request_token_secret
					credentials.save()
					authorize_url = magento.get_authorize_url(request_token)
					return HttpResponseRedirect(authorize_url)
				else:
					session = magento.get_auth_session(credentials.request_token,
											   credentials.request_token_secret,
											   method='POST',
											   data={'oauth_verifier': oauth_verifier})
					request.session["access_token"] = session.access_token
					request.session["access_token_secret"] = session.access_token_secret
					credentials.access_token = request.session["access_token"]
					credentials.access_token_secret = request.session["access_token_secret"]
					credentials.save()
					tok = request.session["access_token"], request.session["access_token_secret"]
					session = magento.get_session(token=tok, signature=None)

					r = session.get(
						'products',
						header_auth=True,
						headers=headers
					)
					if r.status_code==200:
						response=json.loads(r.text)
						images_list=[]
						show_products=[]
						for product_id,product in response.items():
							images_response = session.get(
								'products/{}/images'.format(product_id),
								header_auth=True,
								headers=headers
							)
							image=json.loads(images_response.text)
							if image:
								product["imgurl"]=image[0]["url"]
							for idetail in image:
								images_list.append(idetail["url"])
							product_response = session.get(
								'products/{}'.format(product_id),
								header_auth=True,
								headers=headers
							)

							product_details=json.loads(product_response.text)
							product["qty"]=product_details["stock_data"]["qty"]
							show_products.append(product)
						merchants = AccountDetail.objects.all()
						page = self.request.GET.get('page', 1)
						merchant_list = Paginator(merchants, 20)
						products_list = Paginator(show_products, 12)

						try:
							products_list = products_list.page(page)

magento/templates/merchant/mag_mer_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<title>
{% block title %}
{% endblock %}
</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">


<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
{% block css %}
{% endblock %}
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
</head>
<body>
{% block content %}
{% endblock %}



<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<!-- <script src="{% static 'js/register.js' %}"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script> 
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/magento/magento_merchant.js' %}"></script>

{% block script %}
{% endblock %}


</body>
</html>

magento/templates/merchant/mag_mer_dashboard.html
{% extends "merchant/mag_mer_base.html" %}
{% load staticfiles %}
{% load added %}
{% block title %}
Dashboard
{% endblock %}
{% block css %}
<link  href="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
{% endblock %}
{% block content %}
<div class="container">

		<div id="tabs" class="clearfix">
			<ul class="tabs clearfix" data-tabgroup="first-tab-group">
				<li><a id="1" class="active" href="#home-tab">Home</a></li>
				<li><a id="2" href="#order-tab">Orders</a></li>
			</ul>
		  	<div id="first-tab-group" class="tabgroup">
				<div id="home-tab">
					<div class="product-list-section clearfix">
						<ul class="prodlist-ul">
              {% for product in products %}

                {% if product.id|added:merchant_id %}
                <li class="product-added">
                    <form action="{% url 'mag_mer_remove_product' %}" method="get">
                      <input type="hidden" name="id" value="{{ product.id|added:merchant_id }}">
                {% else %}
                <li>
                    <form action="{% url 'mag_mer_add_product' %}" method="get">
                      <input type="hidden" name="id" value="{{ product.id }}">
                {% endif %}

  								<div class="product-list-div">
                    {% if product.images_set.all|length > 1 %}
  									   <div class="fotorama product-img-wrap" id="images_slider{{ product.id }}" data-width="100%" data-allowfullscreen="true" data-loop="true">
                    {% else %}
                        <div class="fotorama product-img-wrap mvp-custom-class" id="images_slider{{ product.id }}" data-width="100%" data-allowfullscreen="true" data-loop="true">
                    {% endif %}

                      {% if product.images_set.all %}
                        {% for image in product.images_set.all %}
    										   <img src="{{ image.image.url }}">
                        {% endfor %}
                      {% else %}
                         <img src="{% static 'images/img1.jpg' %}">
                      {% endif %}
  									</div>
  									<div class="product-content-wrap" data-id='{{ product.id }}'>
  										<h3 class="product-title">{{ product.title }}</h3>
  										<span class="product-vendor">{{ product.user.first_name|title }}</span>
                      {% if product.isconfig %}
                        {{ product.varient_value|varientdata|safe }}
                      {% endif %}
  										<span class="product-price">{{ product.selling_price }}</span>
  										<div class="add-cart-btn">
                        {% if product.id|added:merchant_id %}
                          <input class="add-to-shop" type="submit" value="Remove from Magento">
                        {% else %}
                          <input class="add-to-shop" type="submit" value="Add to Magento">
                        {% endif %}
  										</div>
  									</div>
  								</div>
                </form>
							</li>
              {% endfor %}
						</ul>
            {% if products.has_other_pages %}
            <div class="pagination">
        			<ul class="pagination-list">
                {% if products.has_previous %}
        				    <li><span class="left-arrow"><a href="?page={{ products.previous_page_number }}&tabv=1"><img src="{% static 'images/left-arrow.png' %}"></a></span></li>
                {% else %}
                   <li class="disabled"><span class="left-arrow"><img src="{% static 'images/left-arrow.png' %}"></span></li>
                {% endif %}
                {% for i in products.paginator.page_range %}
                   {% if products.number == i %}
                     <li class="active"><a href="#">{{ i }}</a></li>
                   {% else %}
                     <li><a href="?page={{ i }}&tabv=1">{{ i }}</a></li>
                   {% endif %}
                {% endfor %}
                {% if products.has_next %}
                   <li><span class="left-arrow"><a href="?page={{ products.next_page_number }}&tabv=1"><img src="{% static 'images/right-arrow.png' %}"></a></span></li>
                {% else %}
                   <li  class="disabled"><span class="left-arrow"><img src="{% static 'images/right-arrow.png' %}"></span></li>
              {% endif %}
        			</ul>
        		</div>
            {% endif %}
					</div>
				</div>
				<div id="order-tab" class="order-tab">
					<div class="order-wrap-row">
						<h3 class="vendor-title">Orders not yet paid to vendor</h3>
            {% if unpaid %}
						<div class="vendor-table">
							<div class="order-head">
								<div class="order-vendor-row">
									<span class="col col-1">Vendor Name</span>
									<span class="col col-2">Total Price</span>
									<span class="col col-3">Order ID</span>
									<span class="col col-4">Action</span>
								</div>
							</div>

							<div class="order-body">
                {% for order in unpaid %}
								<div class="order-vendor-row">
  									<span class="col col-1" title="{{ order.id|vendors }}">{{ order.id|vendors|title }}</span>
  									<span class="col col-2">${{ order.total_amount }}</span>
  									<span class="col col-3">#{{ order.id }}</span>
                    <span class="col col-4">
                      <form action="{% url 'mag_mer_paypal' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ order.id }}">
    									  <button name="action" type="submit"><img src="{% static 'images/paypal.png' %}"></button>
                      </form>
                    </span>
								</div>
                {% endfor %}
								<!-- <div class="order-vendor-row">
									<span class="col col-1">Fashion Circle Test spanbel</span>
									<span class="col col-2">$493.24</span>
									<span class="col col-3">#1022 #1023</span>
									<span class="col col-4"><img src="{% static 'images/paypal.png' %}"></span>
								</div> -->

							</div>
						</div>
            {% else %}
              <div class="no-unpaid-order">No order found.</div>
            {% endif %}
            {% if unpaid.has_other_pages %}
            <div class="pagination">
        			<ul class="pagination-list">
                {% if unpaid.has_previous %}
        				    <li><span class="left-arrow"><a href="?page={{ unpaid.previous_page_number }}&tabv=2"><img src="{% static 'images/left-arrow.png' %}"></a></span></li>
                {% else %}
                   <li class="disabled"><span class="left-arrow"><img src="{% static 'images/left-arrow.png' %}"></span></li>
                {% endif %}
                {% for i in unpaid.paginator.page_range %}
                   {% if unpaid.number == i %}
                     <li class="active"><a href="#">{{ i }}</a></li>
                   {% else %}
                     <li><a href="?page={{ i }}&tabv=2">{{ i }}</a></li>
                   {% endif %}
                {% endfor %}
                {% if unpaid.has_next %}
                   <li><span class="left-arrow"><a href="?page={{ unpaid.next_page_number }}&tabv=2"><img src="{% static 'images/right-arrow.png' %}"></a></span></li>
                {% else %}
                   <li  class="disabled"><span class="left-arrow"><img src="{% static 'images/right-arrow.png' %}"></span></li>
              {% endif %}
        			</ul>
        		</div>
            {% endif %}
					</div><div class="order-wrap-row">
						<h3 class="vendor-title">Orders paid to vendors</h3>
            {% if paid %}
						<div class="vendor-table">
							<div class="order-head">
								<div class="order-vendor-row">
									<span class="col col-1">Vendor Name</span>
									<span class="col col-2">Total Price</span>
									<span class="col col-3">Order ID</span>
									<span class="col col-4">Status</span>
								</div>
							</div>
							<div class="order-body">
                {% for order in paid %}
								<div class="order-vendor-row">
									<span class="col col-1">{{ order.id|vendors|title }}</span>
									<span class="col col-2">${{ order.total_amount }}</span>
									<span class="col col-3">#{{ order.id }}</span>
									<span class="col col-4"><a class="paid-btn" href="javascript:void();">Paid</a></span>
                  {% endfor %}
								</div>
								{% else %}
                  <div class="no-paid-order">No order found.</div>
                {% endif %}
                {% if paid.has_other_pages %}
                <div class="pagination">
            			<ul class="pagination-list">
                    {% if paid.has_previous %}
            				    <li><span class="left-arrow"><a href="?page={{ paid.previous_page_number }}&tabv=2"><img src="{% static 'images/left-arrow.png' %}"></a></span></li>
                    {% else %}
                       <li class="disabled"><span class="left-arrow"><img src="{% static 'images/left-arrow.png' %}"></span></li>
                    {% endif %}
                    {% for i in paid.paginator.page_range %}
                       {% if paid.number == i %}
                         <li class="active"><a href="#">{{ i }}</a></li>
                       {% else %}
                         <li><a href="?page={{ i }}&tabv=2">{{ i }}</a></li>
                       {% endif %}
                    {% endfor %}
                    {% if paid.has_next %}
                       <li><span class="left-arrow"><a href="?page={{ paid.next_page_number }}&tabv=2"><img src="{% static 'images/right-arrow.png' %}"></a></span></li>
                    {% else %}
                       <li  class="disabled"><span class="left-arrow"><img src="{% static 'images/right-arrow.png' %}"></span></li>
                  {% endif %}
            			</ul>
            		</div>
                {% endif %}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>


  	</div>
{% endblock %}
{% block script %}
<script type="text/javascript">

$('.tabgroup > div').hide();
$('.tabgroup > div:first-of-type').show();
$('.tabs a').click(function(e){
  e.preventDefault();
    var $this = $(this),
        tabgroup = '#'+$this.parents('.tabs').data('tabgroup'),
        others = $this.closest('li').siblings().children('a'),
        target = $this.attr('href');
    others.removeClass('active');
    $this.addClass('active');
    $(tabgroup).children('div').hide();
    $(target).show();

})
</script>
{% endblock %}

magento/templates/merchant/mag_mer_forget_password.html
{% extends "merchant/mag_mer_base.html" %}
{% load staticfiles %}
{% block title %}
<title>Forget Password</title>
{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block content %}


<div class="container">

  <div class="row">
      <div class="col-sm-6 col-md-4 col-md-offset-4">
          <h1 class="text-center login-title">Forgot Password! Reset Password from here!</h1>
          <div class="account-wall">
            <label id="mag_vender_forget_email_success_msg" style="display:none;"></label>
            <div class="logo-image">

              <img src="{% static '/images/Logo_Fashioncircle.png' %}" alt="FasionCircle Logo">
            </div>

            {% csrf_token %}

            <div class="forgot_pwd-form">
              <label for="emailid">Email</label>
              <input type="text" name="email"  class="form-control" id="email" placeholder="Enter your email"/>
              <label id="mag_vender_forget_email_msg" class="error" style="display:none;"></label>
              <input type="hidden" id="forgetto" value="{% url 'mag_mer_forget_password' %}">
              <button class="btn btn-lg btn-primary btn-block" id="forget_password_button" type="submit">

              Submit</button>

              <a class="vendor-login" href="{% url 'mag_mer_login' %}">Merchant  Login </a>
            </div>

          </div>
      </div>
  </div>
</div>
{% endblock %}